### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by dirvine** [maidsafe/accumulator#18]
Compiling accumulator v0.0.1 (file:///home/dirvine/Devel/Rust/safe/accumulator)
src/lib.rs:24:22: 24:39 warning: lint unsigned_negation has been removed: replaced by negate_unsigned feature gate
src/lib.rs:24         unsafe_code, unsigned_negation, unused, unused_allocation, unused_attributes,
                                   ^~~~~~~~~~~~~~~~~
src/lib.rs:24:22: 24:39 warning: lint unsigned_negation has been removed: replaced by negate_unsigned feature gate
src/lib.rs:24         unsafe_code, unsigned_negation, unused, unused_allocation, unused_attributes,
                                   ^~~~~~~~~~~~~~~~~

**Comment by chandraprakash** [comment]
fixed in https://github.com/maidsafe/accumulator/pull/19
