### ISSUE TITLE
Initial run of RustFmt

### ISSUE THREAD

**Issue by drrosa** [maidsafe/accumulator#27]
Initial run of RustFmt on libraries that are not being worked on at the moment.

I am tackling this issue myself as part of the code bounty program as suggested by Fraser and approved by David.

**Comment by rosatamsen** [comment]
I am tackling this issue as part of the code bounty program as suggested by Fraser and approved by David.

**Comment by drrosa** [comment]
https://github.com/maidsafe/accumulator/pull/28
